### ISSUE TITLE
requirements.txt file not found

### ISSUE THREAD

**Issue by garrypassarellainfluencer** [gabrielkoo/chatgpt-faq-slack-bot#56]
I'm trying to build this using the deploy.sh file, but when I run it I get the following error

```
requirements.txt file not found. Continuing the build without dependencies.
```

Once the lambda deploys it produces errors because the deps are not found.

Any ideas? I'm on a M3 Macbook and using Python 3.9.

**Comment by gabrielkoo** [comment]
Hi @garrypassarellainfluencer,

That error does not constitute to complete build error. All the necessary Python dependencies are built in the Lambda layer instead in the `layer` directory.

The line `Continuing the build without dependencies.` actually indicates this is not a critical error and build should proceed. But if you do want to supress it, you can create an empty `requirements.txt` file in `./function` directory.

If you don't mind, you can share the full build logs here while redact necessary information.

---

By the way, I created a new repo with similar feature to this repos' application trying to use better AWS-native technologies, 
but it may require more AWS experience.

https://github.com/gabrielkoo/self-learning-rag-it-support-slackbot

**Comment by garrypassarellainfluencer** [comment]
I was able to solve my issue by setting up a virtual environment (I don't use Python that often, so I don't know if not doing this was just down to my ignorance or something worth documenting).

```
python -m venv venv
source venv/bin/activate
```

I also had to pin some dependencies in requirements.txt to solve a weird issue where it would throw `numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject` errors

```
pandas==2.0.1
numpy==1.24.3
```

After this everything worked smoothly :-)
